import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { root } from './site-files.mjs';
import path from 'node:path';

export const escapeHtml = value => String(value).replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);
export async function loadLocales() {
  const dictionaries = Object.fromEntries(await Promise.all(['zh-CN', 'en'].map(async lang => [lang, JSON.parse(await readFile(path.join(root, 'locales', lang + '.json'), 'utf8'))])));
  assert.deepEqual(Object.keys(dictionaries.en).sort(), Object.keys(dictionaries['zh-CN']).sort(), 'Translation keys must match in both locales.');
  for (const [lang, dict] of Object.entries(dictionaries)) for (const [key, value] of Object.entries(dict)) {
    assert(typeof value === 'string' && value.trim(), `${lang}: empty translation ${key}`);
  }
  return dictionaries;
}
export function translateHtml(html, dict) {
  const text = key => { assert(Object.hasOwn(dict, key), `Missing translation: ${key}`); return escapeHtml(dict[key]); };
  html = html.replace(/(<([\w-]+)\b[^>]*\bdata-i18n="([^"]+)"[^>]*>)[^<]*(<\/\2>)/g, (_,open,tag,key,close) => open + text(key) + close);
  return html.replace(/<[\w-]+\b[^>]*>/g, tag => {
    for (const [, attr, key] of tag.matchAll(/\bdata-i18n-(aria-label|alt|content|placeholder|title)="([^"]+)"/g)) {
      tag = tag.replace(new RegExp(`(?<![\\w-])${attr}="[^"]*"`), `${attr}="${text(key)}"`);
    }
    return tag;
  });
}
export const bundleLocales = dictionaries => '// Generated by npm run generate. Edit locales/*.json instead.\nwindow.SITE_TRANSLATIONS = ' + JSON.stringify(dictionaries) + ';\n';
